### ISSUE TITLE
Multiple Project files with SPA in another project

### ISSUE THREAD

**Issue by waywardcode** [brunolau/BrunoLau.SpaServices#1]
Thanks for this fork!

I have an issue, is there a way to force the Node ProjectPath & ContentPath to not be the base project that this lib starts in? 
For example I have multiple projects in VS Solution and my MVC project and my SPA project are in two different places, the way things are working now at startup UseWebpackDevMiddlewareEx looks for the project in which it started in to set the base path for aspnet-webpack and the rest... so we need two node_modules folders. Even with this I have not been successful, I would clone this git and try to fix it myself but I am a bit short on time. Maybe I am overlooking something simple. NodeJS env is not my strong area. Any feedback would be appreciated. Thanks.

**Comment by brunolau** [comment]
Hi, never used it this way, so don't know for sure, but you can try specify WebpackDevMiddlewareOptions such as this

```
app.UseWebpackDevMiddlewareEx(new WebpackDevMiddlewareOptions
{
    HotModuleReplacement = true,
    ProjectPath = "your project path"
});
```

This points the middleware to where the webpack config file is located... You can also try to play with Nove environment variables by using the EnvironmentVariables property of the options

**Comment by waywardcode** [comment]
HI, I tried many combinations, however seems that `EmbeddedResourceReader.Read` is getting it's base path from the assembly which will be the base project path. I am guessing `nodeJSService` : 

` var devServerInfo = nodeJSService.InvokeFromStringAsync<WebpackDevServerInfo>(                EmbeddedResourceReader.Read(typeof(WebpackDevMiddleware), "/Content/Node/webpack-dev-middleware.js"),
args: new object[] { JsonConvert.SerializeObject(devServerOptions, jsonSerializerSettings) }           
).Result;`

runs NodeJS in the base assembly path and `webpack-dev.middleware.js` is using this path to look for 'node_modules' folder and not the 'ProjectPath'.

Thanks for the quick reply.

**Comment by brunolau** [comment]
Resolved in https://github.com/brunolau/BrunoLau.SpaServices/pull/2 , the package v 6.0.0 is now available on NuGet
