### ISSUE TITLE
Any plan to create a version for .NET 6?

### ISSUE THREAD

**Issue by aaroncoderepo** [brunolau/BrunoLau.SpaServices#3]
We are planning on skipping .NET 5 when we migrate from 3.1

**Comment by brunolau** [comment]
Hi, sorry, been very busy recently. I'll try to take a look as soon as possible

**Comment by aaroncoderepo** [comment]
Fantastic, thanks for all the work that you have done.
I have tried to get some alternative options running but did not have any luck.

**Comment by brunolau** [comment]
The package is now available on NuGet, thank you for notifying
